Import('env')

source = Split("""sopwith.cpp""")

defines = ['$CPPDEFINES']
if env['PLATFORM'] == 'win32':
    defines.extend(['random=rand', 'srandom=srand'])
env.Program('sopwith', source, CPPDEFINES=defines)
