Import('env')

source = Split("""sopwith.cpp""")

defines = ['$CPPDEFINES']
if env['PLATFORM'] == 'win32':
    defines.extend(['random=rand', 'srandom=srand'])
    if 'msvc' in env['TOOLS']:
        # TODO: Add AL_PI to base.h and replace M_PI with it in demos/sopwith/sopwith.cpp
        defines.extend(['_USE_MATH_DEFINES'])
env.Program('sopwith', source, CPPDEFINES=defines)
